portfolioproject/accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path 

app_name = 'accounts'

urlpatterns =[
    path('register/', views.register, name = 'register'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
]

portfolioproject/portfolio_app/urls.py
from django.urls import path
from portfolio_app import views
from django.conf.urls import url

app_name = 'portfolio_app'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('contact/', views.contact, name = 'contact'),
    path('blog/', views.blog, name = 'blog'),
    path('create/', views.article_create, name ='create'),
    path('<slug>/', views.article_detail, name = 'detail'),
    
]

portfolioproject/portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio_app import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('', views.index, name = 'index'),
    path('blog/', views.blog, name = 'blog'),
    path('portfolio_app/', include('portfolio_app.urls', 'send.urls')),
    path('accounts/', include('accounts.urls')),
    path('<slug>', views.article_detail, name = 'detail'),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

portfolioproject/accounts/models.py
from django.db import models

# Create your models here.

portfolioproject/portfolio_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default='none', on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50] + '....'


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.name

    

portfolioproject/portfolio_app/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']


class ContactForm(forms.Form):
    model = models.Contact
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

portfolioproject/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('portfolio_app:blog')

    else:

        form = UserCreationForm()
    return render(request, 'accounts/register.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('portfolio_app:blog')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('portfolio_app:blog')

portfolioproject/portfolio_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.core.mail import send_mail
from django.contrib import messages
from django.template.loader import get_template
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
from portfolio_app.forms import ContactForm


# Create your views here.
def index (request):
    return render(request, 'portfolio_app/index.html')

def about (request):
    return render(request, 'portfolio_app/index.html')

def blog (request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'portfolio_app/blog.html', {'articles':articles})

def article_detail (request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'portfolio_app/blog_detail.html', {'article':article})

@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            int = form.save(commit=False)
            int.author = request.user
            int.save()
            return redirect('portfolio_app:blog')
    else: 
        form = forms.CreateArticle()
    return render(request, 'portfolio_app/article_create.html', {'form':form})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data ['name']
            email = form.cleaned_data ['email']
            subject = form.cleaned_data ['subject']
            message = form.cleaned_data ['message']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['isikaume@gmail.com']
            if cc_myself:
                recipients.append(email)

            send_mail(name, email, subject, message, recipients, fail_silently=True)
            messages.success(request, "Your Message has been sent Successfully. Thank You!")
            form = ContactForm()
    else:
        form = ContactForm()
    return render(request, 'portfolio_app/index.html', {'form': form})
       

portfolioproject/accounts/templates/accounts/login.html
{% extends 'portfolio_app/base.html' %}
{% load static %}s

{% block content %}
<h1 class="reg">Log In</h1>
<div class="container">
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

portfolioproject/accounts/templates/accounts/register.html
{% extends 'portfolio_app/base.html' %}
{% load static %}

{% block content %}
<section class="container">
    <h1 class="reg">Register</h1>
    <form class="site-form" action="/accounts/register/" method="post">
        {% csrf_token%}
        {{ form }}
        <input type="submit" value="Register">
    </form>
</section>

{% endblock %}

portfolioproject/templates/portfolio_app/article_create.html
{% extends 'portfolio_app/base.html' %}
{% load static %}

{% block content %}
    <div class="create-article">

        <h2 class="reg">Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'portfolio_app:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>

    </div>
<script src="{% static 'portfolio_app/js/slug.js' %}"></script>
{% endblock %}

portfolioproject/templates/portfolio_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block title %}

{% endblock %}


<head>
    <meta charset="utf-8">
    <title>Isika Ume</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="{% static 'portfolio_app/images/favicon.png' %}" rel="icon">
    <link href="{% static 'portfolio_app/images/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Bootstrap CSS File -->
    <link href="{% static 'portfolio_app/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Libraries CSS Files -->
    <link href="{% static 'portfolio_app/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'portfolio_app/css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'portfolio_app/css/ionicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'portfolio_app/css/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'portfolio_app/css/lightbox.min.css' %}" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="{% static 'portfolio_app/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'portfolio_app/css/mystyle.css' %}" rel="stylesheet">

    <!-- =======================================================
    Theme Name: DevFolio
    Theme URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>
<!--/ Nav Star /-->
<nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll" href="{% url 'index' %}"><em>Isika Ume</em></a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
            aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span></span>
            <span></span>
            <span></span>
        </button>
        <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link js-scroll active" href="{% url 'portfolio_app:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll" href="#about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll" href="#service">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll" href="#work">Work</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll" href="{% url 'blog' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll" href="#contact">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll" href="{% url 'accounts:register'%}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll" href="{% url 'accounts:login' %}">Login</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'portfolio_app:create' %}" class="nav-link js-scroll" id="highlight">Create</a>
                </li>
                <li class="nav-item">
                    <form id="logoutb" class="nav-link js-scroll" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                
                {% endif %}
               
            </ul>
        </div>
    </div>
</nav>
<!--/ Nav End /-->



<body>
    <div class="">

        
            {% block content %}
            
            {% endblock %}
    </div>
</body>




    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="copyright-box">
                        <p class="copyright">&copy; Copyright <strong>DevFolio</strong>. All Rights Reserved</p>
                        <div class="credits">
                            <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=DevFolio
                -->
                            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</section>
<!--/ Section Contact-footer End /-->



<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
<div id="preloader"></div>

<!-- JavaScript Libraries -->
<script src="{% static 'portfolio_app/js/jquery.min.js' %}"></script>
<script src="{% static 'portfolio_app/js/jquery-migrate.min.js' %}"></script>
<script src="{% static 'portfolio_app/js/popper.min.js' %}"></script>
<script src="{% static 'portfolio_app/js/bootstrap.min.js' %}"></script>
<script src="{% static 'portfolio_app/js/easing.min.js' %}"></script>
<script src="{% static 'portfolio_app/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'portfolio_app/js/jquery.counterup.js' %}"></script>
<script src="{% static 'portfolio_app/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'portfolio_app/js/lightbox.min.js' %}"></script>
<script src="{% static 'portfolio_app/js/typed.min.js' %}"></script>
<!-- Contact Form JavaScript File -->
<script src="{% static 'portfolio_app/js/contactform.js' %}"></script> -->

<!-- Template Main Javascript File -->
<script src="{% static 'portfolio_app/js/main.js' %}"></script>

</body>

</html>

portfolioproject/templates/portfolio_app/blog.html
{% extends 'portfolio_app/base.html' %}
{% load static %}


{% block content %}
  <!--/ Intro Skew Star /-->
  <section>
    <div class="intro intro-single route bg-image" style="background-image: url({% static 'portfolio_app/images/overlay-bg.jpg' %})">
      <div class="overlay-mf"></div>
      <div class="intro-content display-table">
        <div class="table-cell">
          <div class="container">
            <h2 class="intro-title mb-4">Blog</h2>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ Intro Skew End /-->

  <!--/ Section Blog-Single Star /-->
  <section>
   
  <div class="wrapper">
    <div class="articles">
    {% for article in articles %}
      <div class="article-blog">
        <h2><a href="{% url 'detail' slug=article.slug %}">{{ article.title }}</a></h2>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">added by {{ article.author.username }}</p>
      </div>
    {% endfor %}
    </div>
  </div>
  
  </section>
  <!--/ Section Blog-Single End /-->
  {% endblock %}

portfolioproject/templates/portfolio_app/blog_detail.html
{% extends 'portfolio_app/base.html' %}
{% load static %}

{% block content %}
<div class="article-detail">
    <div class="article">

        <img src="{{ article.thumb.url }}" alt="">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

portfolioproject/templates/portfolio_app/contact.html
{% extends 'portfolio_app/base.html' %}
{% load static %}

{% block title %}
contact
{% endblock %}

{% block content %}
    <section class="paralax-mf footer-paralax bg-image sect-mt4 route" style="background-image: url({% static 'portfolio_app/images/overlay-bg.jpg' %})">
    <div class="overlay-mf"></div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="contact-mf">
                    <div id="contact" class="box-shadow-full">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="title-box-2">
                                    <h5 class="title-left">
                                        Send Us A Message
                                    </h5>
                                </div>
                                <div>
                                    <form action="." method="post" role="form" class="contactForm">
                                        {% csrf_token %}
                                        <div>
                                        {% for message in messages %}
                                        <h4 style="color: green">{{ message }} </h4> 
                                        {% endfor %}
                                        </div>
                                        <div id="errormessage"></div>
                                        <div class="row">
                                            <div class="col-md-12 mb-3">
                                                <div class="form-group">
                                                    <input type="text" name="name" class="form-control" id="name"
                                                        placeholder="Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                                                    <div class="validation"></div>
                                                </div>
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <div class="form-group">
                                                    <input type="email" class="form-control" name="email" id="email"
                                                        placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                                                    <div class="validation"></div>
                                                </div>
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="subject" id="subject"
                                                        placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                                                    <div class="validation"></div>
                                                </div>
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <div class="form-group">
                                                    <textarea class="form-control" name="message" rows="5" data-rule="required"
                                                        data-msg="Please write something for us" placeholder="Message"></textarea>
                                                    <div class="validation"></div>
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <button type="submit" value="submit" class="button button-a button-big button-rouded">Send
                                                    Message</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="title-box-2 pt-4 pt-md-0">
                                    <h5 class="title-left">
                                        Get in Touch
                                    </h5>
                                </div>
                                <div class="more-info">
                                    <p class="lead">
                                        Thanks for taking an interest in my skills! Fortunately, I am currently open to
                                        co-operation on new and existing
                                        projects. Please either fill out the contact information on the left or email
                                        me at <b>isikaume@gmail.com</b> and we
                                        an set up a meeting either in person or over the phone.
                                    </p>
                                    <ul class="list-ico">
                                        <!-- <li><span class="ion-ios-location"></span> 329 WASHINGTON ST BOSTON, MA 02108</li> -->
                                        <li><span class="ion-ios-telephone"></span> +234-706-426-8381</li>
                                        <li><span class="ion-email"></span> isikaume@gmail.com</li>
                                    </ul>
                                </div>
                                <div class="socials">
                                    <ul>
                                        <li><a href="http://www.facebook.com/isikaume"><span class="ico-circle"><i
                                                        class="ion-social-facebook"></i></span></a></li>
                                        <li><a href="http://www.instagram.com/uminem_u.m.e"><span class="ico-circle"><i
                                                        class="ion-social-instagram"></i></span></a></li>
                                        <li><a href="http://www.twitter.com/uminem16"><span class="ico-circle"><i class="ion-social-twitter"></i></span></a></li>
                                        <li><a href="http://www.pinterest.com/isikaume"><span class="ico-circle"><i
                                                        class="ion-social-pinterest"></i></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 </section>
{% endblock %}